from collections.abc import Callable, Iterable, Iterator, Mapping, MutableMapping
from typing import Literal, ParamSpec, Self, TypeVar, overload

from lxml.etree import _Element
from lxml.html import HtmlElement

from .dom import Element, Node

_DEFAULT = TypeVar("_DEFAULT")
_PARAMETERS = ParamSpec("_PARAMETERS")
_RETURN = TypeVar("_RETURN")

class ElementView:
    def __new__(cls, node: Element) -> Self: ...
    @property
    def node(self) -> Element: ...
    @property
    def tag(self) -> str: ...
    @tag.setter
    def tag(self, value: str) -> None: ...
    @property
    def text(self) -> str | None: ...
    @text.setter
    def text(self, value: str | None) -> None: ...
    @property
    def tail(self) -> str | None: ...
    @tail.setter
    def tail(self, value: str | None) -> None: ...
    @property
    def attrib(self) -> MutableMapping[str, str]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[ElementView]: ...
    @overload
    def __getitem__(self, index: int) -> ElementView: ...
    @overload
    def __getitem__(self, index: slice) -> list[ElementView]: ...
    def __copy__(self) -> ElementView: ...
    def __deepcopy__(self, memo: dict[int, ElementView]) -> ElementView: ...
    @overload
    def get(self, key: str, /) -> str | None: ...
    @overload
    def get(self, key: str, default: _DEFAULT, /) -> str | _DEFAULT: ...
    def set(self, key: str, value: str, /) -> None: ...
    def keys(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def values(self) -> list[str]: ...
    def text_content(self) -> str: ...
    def getparent(self) -> ElementView | None: ...
    def getnext(self) -> ElementView | None: ...
    def getprevious(self) -> ElementView | None: ...
    def getchildren(self) -> list[ElementView]: ...
    def getroottree(self) -> _ElementTree: ...
    def xpath(
        self, path: str, /, **variables: str | float | bool | Node
    ) -> str | float | bool | list[ElementView | Node | str]: ...
    def find(self, path: str, /) -> ElementView | None: ...
    def findall(self, path: str, /) -> list[ElementView]: ...
    def iterfind(self, path: str, /) -> Iterator[ElementView]: ...
    def index(self, child: ElementView, /) -> int: ...
    def iter(self, *tags: str | Iterable[str] | None) -> Iterator[ElementView]: ...
    def iterdescendants(self, *tags: str | Iterable[str] | None) -> Iterator[ElementView]: ...
    def append(self, child: ElementView, /) -> None: ...
    def extend(self, children: Iterable[ElementView], /) -> None: ...
    def remove(self, child: ElementView, /) -> None: ...
    def replace(self, old: ElementView, new: ElementView, /) -> None: ...
    def drop_tag(self) -> None: ...
    def drop_tree(self) -> None: ...
    def makeelement(self, tag: str, attrib: Mapping[str, str] | None = None, **extra: str) -> ElementView: ...
    def insert(self, index: int, child: ElementView, /) -> None: ...
    def clear(self, keep_tail: bool = False) -> None: ...
    def addnext(self, child: ElementView, /) -> None: ...
    def addprevious(self, child: ElementView, /) -> None: ...
    def iterchildren(
        self,
        *tags: str | Iterable[str] | None,
        reversed: bool = False,  # ruff: ignore[builtin-argument-shadowing] - Matches lxml's keyword.
    ) -> Iterator[ElementView]: ...
    def itersiblings(self, *tags: str | Iterable[str] | None, preceding: bool = False) -> Iterator[ElementView]: ...
    def iterancestors(self, *tags: str | Iterable[str] | None) -> Iterator[ElementView]: ...
    def itertext(self, *tags: str | Iterable[str] | None, with_tail: bool = True) -> Iterator[str]: ...

class _ElementTree:
    def getroot(self) -> ElementView: ...

class _ElementXPath:
    def __new__(cls, path: str) -> Self: ...
    @property
    def path(self) -> str: ...
    def __call__(
        self, element: ElementView, /, **variables: str | float | bool | Node
    ) -> str | float | bool | list[ElementView | Node | str]: ...

def _elementtree_context(function: Callable[_PARAMETERS, _RETURN], /) -> Callable[_PARAMETERS, _RETURN]: ...
def _elementtree_document_fromstring(markup: str | bytes, /) -> ElementView: ...
def _elementtree_fromstring(markup: str | bytes, /) -> ElementView: ...
def _elementtree_fragment_fromstring(markup: str, create_parent: str | bool = False) -> ElementView: ...
def _elementtree_from_lxml(source: _Element, /) -> ElementView: ...
def _elementtree_to_lxml(source: ElementView | _Element, /) -> _Element: ...
def _elementtree_to_lxml_html(source: ElementView, /) -> HtmlElement: ...
@overload
def _elementtree_tostring(
    elem: ElementView, encoding: Literal["unicode"] | type[str], method: str = "xml", with_tail: bool = True
) -> str: ...
@overload
def _elementtree_tostring(
    elem: ElementView, encoding: Literal["ascii", "utf-8"] | None = None, method: str = "xml", with_tail: bool = True
) -> bytes: ...
@overload
def _elementtree_tostring(
    elem: ElementView, encoding: str, method: str = "xml", with_tail: bool = True
) -> str | bytes: ...
def _elementtree_element(tag: str, attrib: Mapping[str, str] | None = None, **extra: str) -> ElementView: ...
def _elementtree_subelement(
    parent: ElementView, /, tag: str, attrib: Mapping[str, str] | None = None, **extra: str
) -> ElementView: ...
def _elementtree_strip_tags(tree: ElementView, /, *tags: str | Iterable[str] | None) -> None: ...
def _elementtree_strip_elements(
    tree: ElementView, /, *tags: str | Iterable[str] | None, with_tail: bool = True
) -> None: ...
