from collections.abc import Iterator, Mapping, Sequence
from enum import Enum, IntEnum
from typing import final

def escape(s: str, quote: bool = ...) -> str: ...
def unescape(s: str, /) -> str: ...

class TokenType(IntEnum):
    TEXT = 0
    START_TAG = 1
    END_TAG = 2
    COMMENT = 3
    DOCTYPE = 4

@final
class Token:
    @property
    def type(self) -> TokenType: ...
    @property
    def data(self) -> str | None: ...
    @property
    def tag(self) -> str | None: ...
    @property
    def attrs(self) -> list[tuple[str, str | None]] | None: ...
    @property
    def self_closing(self) -> bool: ...
    @property
    def name(self) -> str | None: ...
    @property
    def public_id(self) -> str | None: ...
    @property
    def system_id(self) -> str | None: ...
    @property
    def force_quirks(self) -> bool: ...
    @property
    def line(self) -> int: ...
    @property
    def col(self) -> int: ...
    def attr(self, name: str, default: str | None = None) -> str | None: ...

@final
class Tokenizer:
    def __init__(self) -> None: ...
    def feed(self, data: str) -> Iterator[Token]: ...
    def close(self) -> Iterator[Token]: ...
    def reset(self) -> None: ...
    def __enter__(self) -> Tokenizer: ...
    def __exit__(self, *exc: object) -> None: ...
    def __iter__(self) -> Iterator[Token]: ...

def tokenize(s: str, /) -> Iterator[Token]: ...
def _tokenize_states(
    text: str, initial_state: str, last_start_tag: str | None = ..., storage_kind: int = ..., /
) -> list[tuple[object, ...]]: ...

class Namespace(Enum):
    HTML = "html"
    SVG = "svg"
    MATHML = "math"

class Node:
    @property
    def parent(self) -> Element | Document | None: ...
    @property
    def children(self) -> Sequence[Node]: ...
    @property
    def next_sibling(self) -> Node | None: ...
    @property
    def previous_sibling(self) -> Node | None: ...
    @property
    def descendants(self) -> Iterator[Node]: ...
    @property
    def ancestors(self) -> Iterator[Element | Document]: ...
    @property
    def next_siblings(self) -> Iterator[Node]: ...
    @property
    def previous_siblings(self) -> Iterator[Node]: ...
    @property
    def following(self) -> Iterator[Node]: ...
    @property
    def preceding(self) -> Iterator[Node]: ...
    @property
    def strings(self) -> Iterator[str]: ...
    @property
    def stripped_strings(self) -> Iterator[str]: ...
    @property
    def text(self) -> str: ...
    @property
    def html(self) -> str: ...
    def find(self, tag: str | None = None, /, **attrs: str) -> Element | None: ...
    def find_all(self, tag: str | None = None, /, **attrs: str) -> Iterator[Element]: ...
    def __iter__(self) -> Iterator[Node]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Node: ...
    def __bool__(self) -> bool: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...

@final
class Element(Node):
    __match_args__ = ("tag",)
    @property
    def tag(self) -> str: ...
    @property
    def namespace(self) -> Namespace: ...
    @property
    def attrs(self) -> Mapping[str, str | list[str] | None]: ...

@final
class Text(Node):
    __match_args__ = ("data",)
    @property
    def data(self) -> str: ...

@final
class Comment(Node):
    __match_args__ = ("data",)
    @property
    def data(self) -> str: ...

@final
class Doctype(Node):
    @property
    def name(self) -> str: ...

@final
class Document(Node):
    @property
    def root(self) -> Element | None: ...

def parse(html: str, /) -> Document: ...
def parse_fragment(html: str, context: str = "div") -> Element: ...
def _parse_tree(html: str, /) -> str: ...
def _parse_fragment(html: str, context: str, /) -> str: ...
def _parse_only(html: str, /) -> None: ...
