"""
Generate src/turbohtml/html_entities.h from the building Python's html data.

The C accelerator binary-searches the HTML5 named-reference table and the
numeric-charref correction tables.  Both are derived from the standard library
(:data:`html.entities.html5` and the private ``html._invalid_*`` tables), which
mirror the WHATWG HTML specification, so this script regenerates the C header to
keep them in sync.

Usage:  python tools/generate_html_entities.py src/turbohtml/html_entities.h
"""

from __future__ import annotations

import sys

# Reuse the stdlib's own numeric-charref tables so the generator stays in lockstep
# with html; these names are private to the module, hence the suppressions below.
from html import _invalid_charrefs, _invalid_codepoints  # noqa: PLC2701  # type: ignore[attr-defined]
from html.entities import html5
from pathlib import Path


def generate(out_path: Path) -> None:
    """Write the generated HTML5 entity-table C header to *out_path*."""
    if (longest := max(len(v) for v in html5.values())) > 2:  # a named ref expands to at most two code points
        msg = f"named value longer than 2 code points: {longest}"
        raise SystemExit(msg)
    max_name_len = max(len(k) for k in html5)

    named = [
        f'    {{"{name}", {len(name)}u, {ord(value[0])}u, {ord(value[1]) if len(value) == 2 else 0}u}},'
        for name in sorted(html5)
        for value in (html5[name],)
    ]
    charrefs = [f"    {{{num}u, {ord(_invalid_charrefs[num])}u}}," for num in sorted(_invalid_charrefs)]
    codepoints = sorted(_invalid_codepoints)
    cps = "\n".join(
        "    " + " ".join(f"{cp}u," for cp in codepoints[i : i + 10]) for i in range(0, len(codepoints), 10)
    )

    out_path.write_text(
        "/* Auto-generated by tools/generate_html_entities.py - do not edit. */\n"
        "/* HTML5 named references and numeric-charref correction tables. */\n\n"
        "typedef struct {\n"
        "    const char *name;\n"
        "    unsigned char name_len;\n"
        "    Py_UCS4 cp0;\n"
        "    Py_UCS4 cp1; /* second code point, or 0 when the value is one char */\n"
        "} html5_entity;\n\n"
        f"#define HTML5_MAX_NAME_LEN {max_name_len}\n"
        f"static const int html5_count = {len(named)};\n"
        "static const html5_entity html5_entities[] = {\n"
        f"{chr(10).join(named)}\n"
        "};\n\n"
        "typedef struct { Py_UCS4 num; Py_UCS4 cp; } html5_charref;\n"
        f"static const int invalid_charref_count = {len(charrefs)};\n"
        "static const html5_charref invalid_charrefs[] = {\n"
        f"{chr(10).join(charrefs)}\n"
        "};\n\n"
        f"static const int invalid_codepoint_count = {len(codepoints)};\n"
        "static const Py_UCS4 invalid_codepoints[] = {\n"
        f"{cps}\n"
        "};\n",
        encoding="utf-8",
    )
    print(f"wrote {out_path}: {len(named)} named, {len(charrefs)} charrefs, {len(codepoints)} codepoints")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    generate(Path(sys.argv[1]))
