"""
Generate src/turbohtml/_c/data/attr_atom.h from the common HTML attribute names.

The finder and CSS selector engine compare attribute identities as integers, not
strings: an attribute name is interned once at element insertion. Names in the
table below get a fixed, compile-time atom (so ``class``/``id``/``href`` resolve
to a constant the selector engine bakes in); every other name is interned per
tree into a dynamic table at parse time. Interning a name is a first-byte bucket
scan over the sorted table here, mirroring tag_atom.h.

The table is sorted by name, so the atom assigned to each entry is its 1-based
position; th_attr_table[atom - 1] therefore recovers the name bytes for an atom
in O(1), which Element.attrs and the serializer use to render names back to text.

Usage:  python tools/generate_attrs.py src/turbohtml/_c/data/attr_atom.h
"""

from __future__ import annotations

import sys
from pathlib import Path

# Attributes the HTML standard defines as space-separated token lists; these
# surface in Element.attrs as a list[str]. Kept as a set so the generated header
# can mark them and tree_type.c can switch on the atom instead of memcmp.
TOKEN_LIST = frozenset([
    "accept-charset",
    "accesskey",
    "archive",
    "class",
    "dropzone",
    "headers",
    "rel",
    "rev",
    "sandbox",
    "sizes",
])

# Common attribute names worth a stable compile-time atom: the token-list set
# plus the names that drive selectors and real markup. Open-ended families
# (data-*, aria-*) are left to the per-tree dynamic table.
COMMON = TOKEN_LIST | frozenset([
    "action",
    "alt",
    "async",
    "autocomplete",
    "autofocus",
    "charset",
    "checked",
    "cols",
    "colspan",
    "content",
    "contenteditable",
    "controls",
    "coords",
    "crossorigin",
    "datetime",
    "decoding",
    "defer",
    "dir",
    "disabled",
    "download",
    "draggable",
    "enctype",
    "encoding",
    "for",
    "form",
    "height",
    "hidden",
    "href",
    "hreflang",
    "http-equiv",
    "id",
    "inputmode",
    "integrity",
    "is",
    "itemprop",
    "itemscope",
    "itemtype",
    "label",
    "lang",
    "list",
    "loading",
    "loop",
    "max",
    "maxlength",
    "media",
    "method",
    "min",
    "multiple",
    "muted",
    "name",
    "nonce",
    "novalidate",
    "open",
    "pattern",
    "ping",
    "placeholder",
    "poster",
    "preload",
    "readonly",
    "referrerpolicy",
    "required",
    "reversed",
    "role",
    "rows",
    "rowspan",
    "selected",
    "shape",
    "slot",
    "span",
    "spellcheck",
    "src",
    "srcset",
    "start",
    "step",
    "style",
    "tabindex",
    "target",
    "title",
    "translate",
    "type",
    "usemap",
    "value",
    "width",
    "wrap",
])


def generate(out_path: Path) -> None:
    """Write the generated attribute-atom C header to *out_path*."""
    names = sorted(COMMON)
    atoms = [f"TH_ATTR_{name.upper().replace('-', '_')}" for name in names]

    enum_lines = "\n".join(f"    {atom}," for atom in atoms)

    table_lines = []
    for name, atom in zip(names, atoms, strict=True):
        token = "1" if name in TOKEN_LIST else "0"
        table_lines.append(f'    {{"{name}", {len(name)}u, {atom}, {token}}},')

    # Names are sorted, so entries sharing a first byte are contiguous;
    # first_index[b] is the offset of the first entry whose name starts with a
    # byte >= b, so the bucket for byte b is [first_index[b], first_index[b + 1]).
    first_index = [len(names)] * 257
    for index, name in enumerate(names):
        first_byte = ord(name[0])
        first_index[first_byte] = min(first_index[first_byte], index)
    running = len(names)
    for byte_value in range(256, -1, -1):
        running = min(running, first_index[byte_value])
        first_index[byte_value] = running
    index_rows = ", ".join(str(first_index[byte_value]) for byte_value in range(257))

    out_path.write_text(
        "/* Auto-generated by tools/generate_attrs.py - do not edit. */\n"
        "/* Common HTML attribute-name atoms for integer-compare matching. */\n\n"
        "#ifndef TURBOHTML_ATTR_ATOM_H\n"
        "#define TURBOHTML_ATTR_ATOM_H\n\n"
        "#include <stdint.h>\n"
        "#include <string.h>\n\n"
        "/* TH_ATTR_UNKNOWN (0) is the absent sentinel. Static atoms run 1..LAST in\n"
        "   sorted name order; dynamic per-tree atoms start at TH_ATTR__DYNAMIC_BASE. */\n"
        "enum th_attr {\n"
        "    TH_ATTR_UNKNOWN = 0,\n"
        f"{enum_lines}\n"
        "    TH_ATTR__DYNAMIC_BASE,\n"
        "};\n\n"
        "typedef struct {\n"
        "    const char *name;\n"
        "    uint8_t name_len;\n"
        "    uint32_t atom;\n"
        "    uint8_t token_list; /* HTML space-separated token attribute */\n"
        "} th_attr_entry;\n\n"
        f"static const int th_attr_count = {len(names)};\n"
        "static const th_attr_entry th_attr_table[] = {\n"
        f"{chr(10).join(table_lines)}\n"
        "};\n\n"
        "/* th_attr_first[c] is the first table index whose name starts with a byte\n"
        "   >= c, so entries beginning with byte c are\n"
        "   [th_attr_first[c], th_attr_first[c + 1]). */\n"
        "static const uint16_t th_attr_first[257] = {\n"
        f"    {index_rows}\n"
        "};\n\n"
        "/* Resolve a lowercased attribute name to its static atom, or TH_ATTR_UNKNOWN\n"
        "   for a name not in the table (the caller then compares names as strings).\n"
        "   Callers guarantee len >= 1. */\n"
        "static inline uint32_t th_attr_atom(const char *bytes, size_t len) {\n"
        "    unsigned char first = (unsigned char)bytes[0];\n"
        "    int stop = th_attr_first[first + 1];\n"
        "    for (int index = th_attr_first[first]; index < stop; index++) {\n"
        "        if (th_attr_table[index].name_len == len &&\n"
        "            memcmp(th_attr_table[index].name + 1, bytes + 1, len - 1) == 0) {\n"
        "            return th_attr_table[index].atom;\n"
        "        }\n"
        "    }\n"
        "    return TH_ATTR_UNKNOWN;\n"
        "}\n\n"
        "#endif /* TURBOHTML_ATTR_ATOM_H */\n",
        encoding="utf-8",
    )
    print(f"wrote {out_path}: {len(names)} atoms")


if __name__ == "__main__":
    generate(Path(sys.argv[1]))
