"""
Generate src/turbohtml/entity_names.h: the codepoint to named-entity table.

The NAMED_ENTITIES serializer formatter renders any character that has an HTML
named reference as ``&name;`` (so U+00E9 becomes ``&eacute;``), matching the
output of BeautifulSoup's ``html`` formatter. That formatter draws on the legacy
HTML4 name set, which the standard library exposes as
``html.entities.codepoint2name``; this script bakes the same mapping into a C
table sorted by codepoint for a binary search at serialization time.

Usage:  python tools/generate_entities.py src/turbohtml/entity_names.h
"""

from __future__ import annotations

import sys
from html.entities import codepoint2name
from pathlib import Path


def generate(out_path: Path) -> None:
    """Write the generated codepoint to entity-name C header to *out_path*."""
    # apos is an XML name absent from the HTML4 set; codepoint2name already omits
    # it. Sort by codepoint so the runtime can binary-search the table.
    entries = sorted(codepoint2name.items())
    rows = "\n".join(f'    {{0x{codepoint:04X}, "{name}"}},' for codepoint, name in entries)

    out_path.write_text(
        "/* Auto-generated by tools/generate_entities.py - do not edit. */\n"
        "/* Codepoint to HTML named-entity table for the NAMED_ENTITIES formatter. */\n\n"
        "#ifndef TURBOHTML_ENTITY_NAMES_H\n"
        "#define TURBOHTML_ENTITY_NAMES_H\n\n"
        "#include <stdint.h>\n\n"
        "typedef struct {\n"
        "    uint32_t codepoint;\n"
        "    const char *name;\n"
        "} th_entity_entry;\n\n"
        f"static const int th_entity_count = {len(entries)};\n"
        "static const th_entity_entry th_entity_table[] = {\n"
        f"{rows}\n"
        "};\n\n"
        "/* The named entity for a codepoint, or NULL when it has none. Binary search\n"
        "   over the codepoint-sorted table. */\n"
        "static inline const char *th_entity_name(uint32_t codepoint) {\n"
        "    int low = 0;\n"
        "    int high = th_entity_count - 1;\n"
        "    while (low <= high) {\n"
        "        int mid = (low + high) / 2;\n"
        "        uint32_t value = th_entity_table[mid].codepoint;\n"
        "        if (value == codepoint) {\n"
        "            return th_entity_table[mid].name;\n"
        "        }\n"
        "        if (value < codepoint) {\n"
        "            low = mid + 1;\n"
        "        } else {\n"
        "            high = mid - 1;\n"
        "        }\n"
        "    }\n"
        "    return NULL;\n"
        "}\n\n"
        "#endif /* TURBOHTML_ENTITY_NAMES_H */\n",
        encoding="utf-8",
    )
    print(f"wrote {out_path}: {len(entries)} entities")


if __name__ == "__main__":
    generate(Path(sys.argv[1]))
